### ISSUE TITLE
How to get a pattern for any sentence by programatically ?

### ISSUE THREAD

**Issue by ahari884** [cmward/hobbs#1]
for two inputs
1) demorefl.txt
contents :
 (S (NP (NNP John) ) (VP (VBD said) (SBAR (-NONE- 0)(S (NP (NNP Mary) ) (VP (VBD likes) (NP (PRP herself) ) ) ) ) ) )

2) demosents.txt
contents : 
(S (NP (NNP John)) (VP (VBD saw) (NP (DT a)(JJ flashy) (NN hat)) (PP (IN at) (NP (DT the) (NN store)))))
(S (NP (PRP He)) (VP (VBD showed) (NP (PRP it))(PP (IN to) (NP (NNP Terrence)))))

How to get these patterns for any sentence given programatically?

**Comment by cmward** [comment]
Those are constituency parses. You need to use a parser such as Stanford NLP's [shift reduce parser ](http://nlp.stanford.edu/software/srparser.shtml)to obtain them. [NLTK](http://www.nltk.org/howto/parse.html) also has parsing functionality, but I don't know if it provides any pre-trained models.
